name: Publish package to GitHub Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  # sync-to-gitlab:
  #   if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
  #   runs-on: ubuntu-latest
  #   name: Gitlab Repo Sync
  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       fetch-depth: 0
  #   - uses: wangchucheng/git-repo-sync@v0.1.0
  #     with:
  #       # Such as https://github.com/wangchucheng/git-repo-sync.git
  #       target-url: ${{ secrets.GLAB_URL }}
  #       # Such as wangchucheng
  #       target-username: ${{ secrets.GLAB_USERNAME }}
  #         # You can store token in your project's 'Setting > Secrets' and reference the name here
  #       target-token: ${{ secrets.GLAB_ACCESS_TOKEN }}

  build-only:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

      - name: Build with Maven
        run: mvn deploy -Dregistry=https://maven.pkg.github.com/maxwellgithinji -Dtoken=$RELEASE_TOKEN
      

  build-and-release:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v11
        with:
          servers:
            '[
              {
                "id": "github",
                "username": "${env.GITHUB_USERNAME}",
                "password": "${env.GITHUB_TOKEN}"
              }
            ]'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          BUILD_ENV: 'github-actions'
          MVN_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
